version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: anonymizer_postgres
    environment:
      POSTGRES_DB: data-anonymizer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  stream-processing:
    build:
      context: ./stream-processing
    container_name: anonymizer_stream-processing
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/data-anonymizer
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/data-anonymizer
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres

volumes:
  postgres_data:
